[package]
name = "lunapdf"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.103"
crossbeam-channel = "0.5.16"
eframe = { version = "0.35.0", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
memory-stats = "1.2.0"
mupdf = { version = "0.8.0", default-features = false, features = ["base14-fonts", "system-fonts"] }
rfd = "0.17.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.27.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",
    "Win32_Storage_Xps",
    "Win32_UI_Controls_Dialogs",
] }

[profile.release]
strip = "symbols"
